name: change-detector
on:
  push:
    paths:
      - 'test/sub/**'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Slack App
        run: |-
          curl -X POST -H "Content-Type: application/json" -d '${{ toJSON(github) }}' ${{ secrets.REQUEST_URL }}